# Generated by Django 3.0.6 on 2020-07-21 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20200719_0904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversationmessage',
            options={'ordering': ['timestamp']},
        ),
    ]
