# Generated by Django 3.0.6 on 2020-07-21 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20200721_1652'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversationmessage',
            options={'ordering': ['-timestamp']},
        ),
    ]
