# Generated by Django 3.0.6 on 2020-07-21 16:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_conversations_last_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversations',
            name='last_contact',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
