# Generated by Django 3.0.6 on 2020-07-21 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_auto_20200721_1756'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversations',
            options={'ordering': ['-last_contact']},
        ),
    ]
