# Generated by Django 3.0.6 on 2020-07-27 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_conversationmessage_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationmessage',
            name='attachment',
            field=models.ImageField(blank=True, upload_to='attachments'),
        ),
    ]
