# Generated by Django 3.0.6 on 2020-08-04 19:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_auto_20200804_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationmessage',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
    ]
