# Generated by Django 3.0.6 on 2020-08-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_conversationmessage_vocie_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversations',
            name='last_message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
