# Generated by Django 3.0.6 on 2020-05-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='age_gender',
            name='about',
            field=models.TextField(default='Describe Yourself'),
        ),
        migrations.AddField(
            model_name='age_gender',
            name='age_range',
            field=models.CharField(default='Describe Yourself', max_length=30),
        ),
        migrations.AddField(
            model_name='age_gender',
            name='drinking',
            field=models.CharField(default='Describe Yourself', max_length=30),
        ),
        migrations.AddField(
            model_name='age_gender',
            name='interested_in',
            field=models.CharField(default='Describe Yourself', max_length=30),
        ),
        migrations.AddField(
            model_name='age_gender',
            name='location',
            field=models.CharField(default='Describe Yourself', max_length=50),
        ),
        migrations.AddField(
            model_name='age_gender',
            name='looking_for',
            field=models.CharField(default='Describe Yourself', max_length=30),
        ),
        migrations.AddField(
            model_name='age_gender',
            name='religion',
            field=models.CharField(default='Describe Yourself', max_length=30),
        ),
        migrations.AddField(
            model_name='age_gender',
            name='smoking',
            field=models.CharField(default='Describe Yourself', max_length=30),
        ),
    ]
