# Generated by Django 3.0.6 on 2020-05-20 22:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('User', '0002_auto_20200520_1845'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Age_gender',
            new_name='Profile',
        ),
    ]
