# Generated by Django 3.0.6 on 2020-05-31 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='age_range',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='religion',
        ),
        migrations.AddField(
            model_name='profile',
            name='maximum_age',
            field=models.PositiveIntegerField(default=99, max_length=3),
        ),
        migrations.AddField(
            model_name='profile',
            name='minimum_age',
            field=models.PositiveIntegerField(default=18, max_length=3),
        ),
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='drinking',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interested_in',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='looking_for',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='smoking',
            field=models.CharField(default='', max_length=30),
        ),
    ]
