# Generated by Django 3.0.6 on 2020-06-15 19:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('User', '0006_auto_20200531_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='maximum_age',
            field=models.PositiveIntegerField(default=99, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='minimum_age',
            field=models.PositiveIntegerField(default=18, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pictures', models.ImageField(upload_to='profile_pics')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
