# Generated by Django 3.0.6 on 2020-06-18 14:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('User', '0011_auto_20200618_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='like',
            field=models.ManyToManyField(related_name='profile_pages', to=settings.AUTH_USER_MODEL),
        ),
    ]
